FROM python:3.7.1

COPY . /app
WORKDIR /app

RUN pip install -r requirements.txt

# Ensures the log messages are printed in out in a timely fashion
# https://github.com/awslabs/amazon-sagemaker-examples/issues/319
ENV PYTHONUNBUFFERED=1

CMD ["python", "-u", "testit.py"]
