{
 "title": "Speedtest",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "machine_name",
    "label": "Machine Name",
    "query": "{\"find\": \"terms\", \"field\": \"fields.machine\"}"
   }
  ]
 },
 "panels": [
  { "title": "Speedtest", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Machines With Network Issues",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "fields.machine",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "internet-accessable:no OR route_to_host:no",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Average Download",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "format": "bps",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "download",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "fields.machine:$machine_name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Average Upload",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "format": "bps",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "upload",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "fields.machine:$machine_name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Average Ping",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "ping",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "fields.machine:$machine_name",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Ping Testing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Avg Ping Time To Gateway",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "avg_ping_time",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "doctype:ping-metrics AND fields.machine:$machine_name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Avg Packet Loss To Gateway",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "packet_loss",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "doctype:ping-metrics  AND fields.machine:$machine_name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Route To Gateway Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "route_to_host",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "doctype:ping-metrics  AND fields.machine:$machine_name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Download Speed Histogram",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "download",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "fields.machine:$machine_name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Upload Speed Histogram",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "upload",
       "id": "1",
       "meta": {},
       "settings": { "missing": 0 },
       "type": "avg"
      }
     ],
     "query": "fields.machine:$machine_name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Machine Checkins",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "fields.machine",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "100" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Internet Accessable",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "internet-accessable",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "fields.machine:$machine_name",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}